### ISSUE TITLE
Crash bot

### ISSUE THREAD

**Issue by Distrib-ps** [busybox11/probote-v2#16]
Le bot à tendance à crash après quelque temps : http://prntscr.com/vjgpgp

**Comment by busybox11** [comment]
Hm, en effet.
Tu pourrais lancer le bot en activant la stack trace ?

**Comment by Distrib-ps** [comment]
Yep, pourrais-tu me dire comment faire ?

**Comment by busybox11** [comment]
Lance le bot avec `node --trace-warnings index.js`

**Comment by Distrib-ps** [comment]
http://prntscr.com/vjhcvi

**Comment by busybox11** [comment]
Hmm... Ca n'a strictement rien changé par rapport à ce que je voulais obtenir.

Tu pourrais le lancer avec un debugger et me dire d'où vient l'erreur stp ?

**Comment by Distrib-ps** [comment]
Comment ça http://prntscr.com/vjiuum ?

**Comment by busybox11** [comment]
C'est ça. Quand il y a l'erreur normalement il s'arrête et il t'ouvre le fichier avec la ligne responsable de l'erreur, ici ça a fait quoi ?

**Comment by Distrib-ps** [comment]
Il n'ouvre rien, juste ce message. Toutes les commandes liées à pronote ne fonctionne plus, mais le reste fonctionne (proinvite etc)

**Comment by busybox11** [comment]
Hm, c'est vraiment bizarre. Le debugger ne s'arrête même pas ? 

Tu as bien sélectionné `NodeJS` dans le debugger VSCode ?

**Comment by Distrib-ps** [comment]
Yep

**Comment by busybox11** [comment]
Ça se fait automatiquement ou quand tu fais une certaine commande ?

Je te recommanderais de lancer le bot avec pm2 et de regarder les logs après un certain temps, ça serait pratique pour les erreurs.

**Comment by Distrib-ps** [comment]
Automatiquement, au bout d'un certains temps il va afficher cette erreur.
Habituellement je le fais avec `node index.js`. Je vais essayer.

**Comment by Distrib-ps** [comment]
Il faut bien `pm2 start index.js` ?
Car après quand je stop je n'ai rien http://prntscr.com/vjk7rz

**Comment by busybox11** [comment]
Hm. Oui normalement c'est comme ça.
Tu as quoi dans `pm2 logs 0` ?

**Comment by Distrib-ps** [comment]
http://prntscr.com/vjk92k

**Comment by busybox11** [comment]
Ok, je l'ai. Ça sera surement corrigé demain !

**Comment by Distrib-ps** [comment]
D'acc, thx !

**Comment by busybox11** [comment]
Merci à toi :)
