### ISSUE TITLE
Copier .env.example vers .env et modifier les valeurs correspondantes 

### ISSUE THREAD

**Issue by AXXIAR** [busybox11/probote-v2#21]
Hello je connais mal ce genre de procédure. Je ne comprend pas vraiment comment faire la partie Copier .env.example vers .env et modifier les valeurs correspondantes

**Comment by busybox11** [comment]
Hey
Il suffit juste de copier le fichier `.env.example` vers un fichier appelé `.env`.

Pour les valeurs, je suis en train d'écrire un guide (j'ai beaucoup de retard mais je suis en train de le faire).
N'hésite pas à demander pour ce que tu ne comprends pas sur cette issue, mais je vais fermer cette issue.

**Comment by AXXIAR** [comment]
super ! merci 
juste un petit truc : comment je trouve ce fichier en question car je n'ai rien installé à part node.js et la cmd github

**Comment by busybox11** [comment]
Tu as téléchargé le repo du bot sur ton serveur ?

**Comment by AXXIAR** [comment]
ah non j'ai exécuté la commande dans github bash

**Comment by AXXIAR** [comment]
`git clone https://github.com/busybox11/probote-v2` celle là

**Comment by AXXIAR** [comment]
Bon au pire je vais attendre le guide. Merci encore

**Comment by busybox11** [comment]
Hmm... De ce que je vois le problème n'est pas que la configuration mais aussi l'installation.

Essaye déjà d'installer les dépendances avec npm et puis ensuite dis-moi si tu as réussi ^^
