### ISSUE TITLE
Problème publication de note

### ISSUE THREAD

**Issue by Distrib-ps** [busybox11/probote-v2#22]
Salut, depuis plusieurs jours j'ai un problème avec la publication de note automatique. Il y a encore le problème d'inactivité de la session. Mais cette fois-ci, quand une note est publiée nous avons cette erreur : http://prntscr.com/vrdgor

Bonne journée !

**Comment by busybox11** [comment]
Raah, je n'arrive pas à reproduire ce bug !
Tu n'es pas le premier à le reporter...
Est-ce que quand tu vas dans tes notes Pronote, la page par défaut c'est le deuxième trimestre ?

**Comment by Distrib-ps** [comment]
Effectivement, c'est bien le deuxième trimestre

**Comment by busybox11** [comment]
J'imagine qu'il est vide ?

**Comment by Distrib-ps** [comment]
Yep, y a juste des nouvelles note pour le T1, mais page par defaut vide T2

**Comment by busybox11** [comment]
Ookay, je vois ce que c'est.
Merci, je vais voir ça !

**Comment by Distrib-ps** [comment]
Thx !

**Comment by busybox11** [comment]
Désolé je réouvre l'issue, j'en ai besoin :')

**Comment by busybox11** [comment]
Bon, finalement c'est un peu un edge case chiant. J'ai pas vraiment eu le temps de m'en occuper en temps voulu et maintenant c'est un peu trop tard, désolé...
Je le place en wontfix pour le moment, je verrais ça si possible après.
