### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by OMisterDarkO** [busybox11/probote-v2#36]
Bonjour,

J'ai trouvé votre projet très utilise pour nous élève, et donc j'ai voulu directement l'installer sur le Serveur Discord de notre classe, mais j'ai rencontré un problème, en modifient le fichier `.env`, il faut renseigner l'ID et le MPD pour se connecter a notre compte Pronote, mais il se trouve que dans mon établissement, nous nous connectons via l'ENT, donc que dois-je renseigner pour que le bot se connecte ?
J'ai bien renseigné le lien vers "mon" Pronote (sans `/eleve.html`), et mis mes ID et MDP ENT dans le fichier `.env` (qui porte ce même nom, il n'y a rien avant le `.env`).
Lorsque je met le lien Pronote que j'ai mis plus haut, dans un navigateur et que je copie/colle l'ID et le MDP , j'arrive à me connecter en revanche lorsque je lance le Bot celui-ci me dit "Mauvais identifiants".

Merci d'avance pour votre retour.

**Comment by Akuramu** [comment]
Bonjour,

Il faut bien mettre les identifiants utilisés dans votre ENT en précisant le CAS de votre ENT (exemple pour MonLycée.net : iledefrance)

**Comment by OMisterDarkO** [comment]
Bonjour,

Tout d'abord merci pour votre réponse qui était rapide.
Je reviens vers vous, car j'ai quelque petite question accompagné d'erreur que j'ai rencontré; alors déjà sur la liste des fonctionnalités présentes sur votre page Github, tout fonctionne parfaitement à part "Trimestre" qui n'apparaît nul part dans votre code (en tout cas, je n'ai pas trouvé), ma question est est-ce normal ?
Et puis j'ai pu lancer le Bot à l'aide de votre aide sans problème ce matin, et puis cette après-midi, j'ai voulu le relancer, et je suis tombé sur une erreur (c'est le lien si dessous), elle n'est pas vraiment importante, mais j'aimerais quand même pouvoir la régler, comment puis-je faire ?

https://cdn.discordapp.com/attachments/747103861055029301/824644151781359616/Sans_titre.png

Merci d'avance pour votre retour, et bonne journée à vous.

**Comment by busybox11** [comment]
Bonjour,
Excusez-moi du temps de réponse, je suis très peu actif en ce moment, je ne viens pas souvent ici...

Merci à @Akuramu de sa réponse, ça me fait très plaisir !

> Je reviens vers vous, car j'ai quelque petite question, sur la liste des fonctionnalités présentes sur votre page Github, tout fonctionne parfaitement à part "Trimestre" qui n'apparaît nul part dans votre code (en tout cas, je n'ai pas trouvé), ma question est : est-ce normal quel ne fonctionne pas ?
Si j'ai bien compris, c'est un bug connu que je n'arrive pas à régler. En fait, Pronote change le trimestre par défaut en avance par rapport au Lycée, ce qui a pour effet de ne pas avoir de contenu pendant un certain temps - car le trimestre n'est pas commencé.
Ca reprend donc l'erreur de #33.
Je vais essayer de m'y repencher bientôt mais le temps et la motivation ne sont pas tout le temps présents malheureusement... :/
Je vais tout de même essayer de faire le plus possible et de régler ça au plus vite !

Merci à vous deux et bonne journée également :)

**Comment by OMisterDarkO** [comment]
Rebonjour, 

Il n'y a aucun souci, vous répondez dans la journée cela me va largement.
J'ai encore trouvé un petit bug, rien de bien dérangent ; la note minimum est de `0`, et sur Discord, dans l'ambed, il est écrit `-1`, je me doute bien que cela est `0`, mais c'était juste pour vous le signaler.
![image](https://user-images.githubusercontent.com/69794891/112523288-e7e7a800-8d9e-11eb-811f-8fd6abf6028f.png)
![image](https://user-images.githubusercontent.com/69794891/112523305-ec13c580-8d9e-11eb-8b9b-0d77f36add8d.png)

Et puis j'ai un code erreur, et je voulais savoir si cela impacte sur quoi que se soit, ou alors je peux juste ne pas y faire attention.
Je l'ai lancé toute l'après-midi pour tester, et puis voir ce qu'il faisait ; et sans aucune raison, j'ai eux ces erreurs (je connais déjà la deuxième, vous me l'avez expliqué juste avant), mais pour l'erreur `code : -1`, je me demandai si je dois m'inquiéter ou pas du tout.

Sur ce merci beaucoup à vous, et bonne journée.

**Comment by OMisterDarkO** [comment]
SI, si il y avais un message l'accompagnant, le voici :
![image](https://user-images.githubusercontent.com/69794891/112526752-95a88600-8da2-11eb-91b4-9b5848b1ec81.png)

**Comment by busybox11** [comment]
Ah ben le voilà le problème. Je pense que tu as trop fait de requêtes à Pronote d'un coup, arrête le bot pour 1 jour environ et laisse le tourner tranquillement ensuite !

**Comment by OMisterDarkO** [comment]
Ok, je vais faire ça, et je te redit après demain si j'ai encore le problème (le but est de le laisser sur un VPS 24h/24h et 7j/7j).

**Comment by busybox11** [comment]
Nickel, merci !
Yes je vois bien, je fais la même chose et ça marche très bien !

**Comment by OMisterDarkO** [comment]
Et bien moi j'ai des erreurs en plus : 
![image](https://user-images.githubusercontent.com/69794891/112535408-8e867580-8dac-11eb-943b-435601f484e5.png)
Après le bot continu à fonctionner, et puis il se reconnecte tout seul, donc bon, du moment qu'il fonctionne moi ça me va.
Mais je vais l'éteindre demain ou après demain, et je vous fais un retour Samedi ou Dimanche sur les erreurs que j'ai rencontré (autre que celle que je vous ai parlée).

Sur ce bonne soirée à vous.

**Comment by OMisterDarkO** [comment]
Je viens de remarquer que j'ai le code erreur `-1` lorsque je me connecte à mon compte Pronote et que le Bot est connecter aussi, donc je voulais vous demander si vous aussi vous avez ce problème lorsque vous vous connectez en même temps que le bot.

Sur ce, je vous laisse pour ce soir, et je pense ne pas être disponible demain, donc bonne soirée à vous.

**Comment by busybox11** [comment]
Hmm, je n'ai pas ces erreurs là mais je pense savoir d'où elles viennent (la moyenne est donc vide, ça viendrait potentiellement de là). Je ferais des tests ASAP.
Merci du rapport !

Bonne soirée, à bientôt !

**Comment by Akuramu** [comment]
Yep, C’est que l’ip est bannie par le CAS, en île de France le ban dure approximativement 3/4 jours

**Comment by Androz2091** [comment]
Sympa. Vous faites comment en pratique quand vous vous trompez de mot de passe plusieurs fois de suite ? Vous attendez 3 jours ou vous utilisez un VPN ?

**Comment by Akuramu** [comment]
J’ai rattaché deux ip sur mon VPS (je suis chez OVH), quand l’une est bannie, je passe sur la seconde.

**Comment by busybox11** [comment]
> Sympa. Vous faites comment en pratique quand vous vous trompez de mot de passe plusieurs fois de suite ? Vous attendez 3 jours ou vous utilisez un VPN ?

J'ai pas ce problème, on n'a pas de CAS dans mon lycée ¯\_(ツ)_/¯

**Comment by OMisterDarkO** [comment]
Et bien je l'ai leader toute la nuit tranquille (le bot) et je l'ai relancer ce matin; et depuis il s'est reload 161 fois, et j'arrête pas d'avoir deux erreurs, l'une est : "session inactive ou fermer"; la second est : "adresse IP suspendu".

Après il continu à fonctionner, juste il rep pas tout le temps ....

**Comment by busybox11** [comment]
J'imagine que votre ENT est assez restrictif sur les connexions ¯\_(ツ)_/¯

Je verrais si je peux debugger tout ça. Je garantis rien tho.

**Comment by OMisterDarkO** [comment]
Je n'en sais rien ...
Mais en tout cas même si vous n'y arrivez pas je te remercie de l'aide que vous nous apportez.
_PS: es-t'il possible de parler avec vous sur DIscord, je trouve cela plus simple que sur Github, vous y voyez un inconvénient ?_

Sur ce bonne soirée à vous.

**Comment by busybox11** [comment]
Moi non plus malheureusement :/

Pas de problème, c'est normal !
Pas de problème non plus, il est sur mon profil GH, DMs opened!

À vous (toi ?) aussi !

**Comment by OMisterDarkO** [comment]
Ok très bien, je viens de vous envoyer une demande.
