### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by Spartix** [busybox11/probote-v2#52]
salut, en voulant essayer le bot j'ai vu que le module de l api de pronote avait ete delete .
Aurez vous encore les modules quelque part par hasard ?
Merci d'avance

**Comment by busybox11** [comment]
Hey,
Non, je n'ai pas de sauvegarde du module.
Par contre, il me semble que @VoXaN24 en a une.

**Comment by VoXaN24** [comment]
[https://gitlab.com/VoXaN24/api-pronote](https://gitlab.com/VoXaN24/api-pronote)
Ur Welcome
