### ISSUE TITLE
Uncaught Error: Cannot find module 'pronote-api'

### ISSUE THREAD

**Issue by Steelpex** [busybox11/probote-v2#55]
J'ai un problème quand je lance le index.js sa me dit " Uncaught Error: Cannot find module 'pronote-api' " . Quelqu'un peut m'aider svp ?

![image](https://user-images.githubusercontent.com/68108563/123609558-0a56ea80-d800-11eb-94f8-6fe44942370a.png)

PS : J'ai bien fait comme dans les instructions !

**Comment by busybox11** [comment]
Hey, malheureusement c'est normal, le module API Pronote n'existe plus car il a été saisi par Index Éducation et supprimé par la suite (car détournement d'utilisation de leur service non autorisé).
Il existe une sauvegarde de ce module sur Internet (indice : gitlab d'un certain voxan, je ne peux pas te dire précisément), ce pourquoi je garde le repo actif, mais je ne peux plus fournir de support, malheureusement.
