### ISSUE TITLE
Remise en fonction du bot

### ISSUE THREAD

**Issue by mlebrun40** [busybox11/probote-v2#90]
Afin de refaire fonctionner le bot merci de changer de librairie car pronote-api de Litarvan à été supprimé voici un fork de celui ci https://www.npmjs.com/package/pronote-api-again

**Comment by busybox11** [comment]
Bonsoir,
Même si j'apprécie votre partage de la nouvelle librairie, je ne vais pas implémenter celle ci, du moins pas maintenant.
Si vous voulez contribuer, libre à vous de proposer une pull request.
Merci et bonne soirée

**Comment by mlebrun40** [comment]
Pas de soucis je mis remet ce-soir ; )

Merci beaucoup,
Cordialement Maxence Lebrun
maxencedev.fr
